app/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, PasswordField, SubmitField, BooleanField
from wtforms.ext.sqlalchemy.orm import QuerySelectField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_login import current_user
from app.models import Source, User


roles_list = [('admin', 'Admin'), ('source', 'Source')]

class UserForm(FlaskForm):
    firstname = StringField('First Name', validators=[DataRequired(), Length(min=2, max=20)])
    lastname = StringField('Last Name', validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()], render_kw={"placeholder": "example@email.com"})
    phone = StringField('Phone', validators=[DataRequired(), Length(min=10, max=10)], render_kw={"placeholder": "3334445555","pattern": "[0-9]{10}"})
    fax = StringField('Fax', validators=[Length(min=0, max=10)], render_kw={"placeholder": "3334445555"})
    job_type = StringField('Job Type')
    role = SelectField('Role', choices=roles_list)
    # source_id = SelectField('Source', coerce=int)
    source_id = QuerySelectField('Source', query_factory=lambda: Source.query.all(), get_label='name', validators=[DataRequired()])
    submit = SubmitField('Save')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('That email is taken. Please choose a different one.')

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()], render_kw={"placeholder": "example@email.com"})
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError('There is no account with that email. Please check the email.')

class RequestResetForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()], render_kw={"placeholder": "example@email.com"})
    submit = SubmitField('Request Password Reset')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError('There is no account with that email. You must register first.')

class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')]) 
    submit = SubmitField('Reset Password')

app/users/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, session, Blueprint
from flask_login import login_user, current_user, logout_user, fresh_login_required
from app import app, db, bcrypt
from app.models import User, Referral, Source
from app.users.forms import LoginForm, UserForm, RequestResetForm, ResetPasswordForm
from app.utils import send_reset_email, send_new_account_email

users = Blueprint('users', __name__)


@users.route("/user/list")
@fresh_login_required
def list_users():
    user = User.query.get(current_user.id)
    if user.role == 'admin':      
        users = User.query.all()
        return render_template('users/users_list.html', title="Users", users=users)
    else:
        abort(403)


@users.route("/user/new", methods=['GET', 'POST'])
@fresh_login_required
def new_user():
    sources = Source.query.all()
    form = UserForm()
    if form.validate_on_submit():
        user = User(firstname=form.firstname.data,lastname=form.lastname.data, email=form.email.data.lower(), phone=form.phone.data, fax=form.fax.data, role=form.role.data, source_id=form.source_id.data)
        db.session.add(user)
        db.session.commit()
        send_new_account_email(user)
        flash('The User was created successfully.', 'success')
        return redirect(url_for('users.login'))
    return render_template('users/crud_user.html', title='Create User', form=form, sources=sources)


@users.route("/user/<int:user_id>")
@fresh_login_required
def user(user_id):
    user = User.query.get_or_404(user_id)
    return render_template('users/user.html', title="User Info", user=user)


@users.route("/user/<int:user_id>/update", methods=['GET', 'POST'])
@fresh_login_required
def crud_user(user_id):
    user = User.query.get_or_404(user_id)
    if current_user.role != 'admin':
         abort(403)
    form = UserForm()
    if form.validate_on_submit():
        user.firstname=form.firstname.data
        user.lastname=form.lastname.data
        user.email=form.email.data.lower()
        user.phone=form.phone.data
        user.fax=form.fax.data
        user.job_type=form.job_type.data
        user.role=form.role.data
        user.source_id=form.source_id.data
        db.session.commit()
        flash('The User was updated successfully.', 'success')
        return redirect(url_for('users.user',user_id=user.id))
    elif request.method == 'GET':
        sources = Source.query.all()
        form.firstname.data=user.firstname
        form.lastname.data=user.lastname
        form.email.data=user.email
        form.phone.data=user.phone
        form.fax.data=user.fax
        form.job_type.data=user.job_type
        form.role.data=user.role
        form.source_id.data=user.source_id
    return render_template('users/crud_user.html', title='Update User', form=form)


@users.route("/user/<int:user_id>/delete", methods=['POST'])
@fresh_login_required
def delete_user(user_id):
    user = User.query.get_or_404(user_id)
    if current_user.role != 'admin':
        abort(403)
    db.session.delete(user)
    db.session.commit()
    flash('The User was deleted successfully.', 'success')
    return redirect(url_for('users.list_users'))


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password.', 'danger')
    return render_template('users/login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

                
@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():    
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('users/reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('users/reset_token.html', title='Reset Password', form=form) 

app/templates/users/create_user.html
{% extends "layout.html" %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            {{ form.firstname.label(class="form-control-label") }}
                            {% if form.firstname.errors %}
                                {{ form.firstname(class="form-control form-control-sm is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.firstname.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.firstname(class="form-control form-control-sm") }}
                            {% endif %}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.lastname.label(class="form-control-label") }}
                            {% if form.lastname.errors %}
                                {{ form.lastname(class="form-control form-control-sm is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.lastname.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.lastname(class="form-control form-control-sm") }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            {{ form.email.label(class="form-control-label") }}
                            {% if form.email.errors %}
                                {{ form.email(class="form-control form-control-sm is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.email(class="form-control form-control-sm") }}
                            {% endif %}
                        </div>
                        <div class="form-group col-md-4">
                            {{ form.phone.label(class="form-control-label") }}
                            {% if form.phone.errors %}
                                {{ form.phone(class="form-control form-control-sm is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.phone.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.phone(class="form-control form-control-sm") }}
                            {% endif %}
                        </div>
                        <div class="form-group col-md-4">
                            {{ form.fax.label(class="form-control-label") }}
                            {% if form.fax.errors %}
                                {{ form.fax(class="form-control form-control-sm is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.fax.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.fax(class="form-control form-control-sm") }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            {{ form.role.label(class="form-control-label") }}
                            {% if form.role.errors %}
                                {{ form.role(class="form-control form-control-sm is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.role.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.role(class="form-control form-control-sm") }}
                            {% endif %}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.source_id.label(class="form-control-label") }}
                            {% if form.source_id.errors %}
                                {{ form.source_id(class="form-control form-control-sm is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.source_id.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                <select class="form-control form-control-sm" id="source_id" name="source_id">
                                    {% for source in sources %}
                                        <option value="{{ source.id }}">{{ source.name }}</option>
                                    {% endfor %}
                                </select>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-row d-flex justify-content-end">
                        <div class="form-group">
                            {{ form.submit(class="btn btn-outline-info") }}
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

app/templates/users/crud_user.html
{% extends "layout.html" %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            {{ form.firstname.label(class="form-control-label") }}
                            {% if form.firstname.errors %}
                                {{ form.firstname(class="form-control form-control-sm is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.firstname.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.firstname(class="form-control form-control-sm") }}
                            {% endif %}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form.lastname.label(class="form-control-label") }}
                            {% if form.lastname.errors %}
                                {{ form.lastname(class="form-control form-control-sm is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.lastname.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.lastname(class="form-control form-control-sm") }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            {{ form.email.label(class="form-control-label") }}
                            {% if form.email.errors %}
                                {{ form.email(class="form-control form-control-sm is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.email(class="form-control form-control-sm") }}
                            {% endif %}
                        </div>
                        <div class="form-group col-md-4">
                            {{ form.phone.label(class="form-control-label") }}
                            {% if form.phone.errors %}
                                {{ form.phone(class="form-control form-control-sm is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.phone.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.phone(class="form-control form-control-sm") }}
                            {% endif %}
                        </div>
                        <div class="form-group col-md-4">
                            {{ form.fax.label(class="form-control-label") }}
                            {% if form.fax.errors %}
                                {{ form.fax(class="form-control form-control-sm is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.fax.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.fax(class="form-control form-control-sm") }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            {{ form.role.label(class="form-control-label") }}
                            {% if form.role.errors %}
                                {{ form.role(class="form-control form-control-sm is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.role.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.role(class="form-control form-control-sm") }}
                            {% endif %}
                        </div>
                        <div class="form-group col-md-4">
                            {{ form.job_type.label(class="form-control-label") }}
                            {% if form.job_type.errors %}
                                {{ form.job_type(class="form-control form-control-sm is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.job_type.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.job_type(class="form-control form-control-sm") }}
                            {% endif %}
                        </div>
                        <div class="form-group col-md-4">
                            {{ form.source_id.label(class="form-control-label") }}
                            {% if form.source_id.errors %}
                                {{ form.source_id(class="form-control form-control-sm is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.source_id.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.source_id(class="form-control form-control-sm") }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-row d-flex justify-content-end">
                        <div class="form-group">
                            {{ form.submit(class="btn btn-outline-info") }}
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

app/templates/users/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <div class="form-group">
                            {{ form.email.label(class="form-control-label") }}
                            {% if form.email.errors %}
                                {{ form.email(class="form-control form-control-sm is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.email(class="form-control form-control-sm") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.password.label(class="form-control-label") }}
                            {% if form.password.errors %}
                                {{ form.password(class="form-control form-control-sm is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.password.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.password(class="form-control form-control-sm") }}
                            {% endif %}
                        </div>
                        <div class="form-check">
                            {{ form.remember(class="form-check-input") }}
                            {{ form.remember.label(class="form-check-label") }}
                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info") }}
                        <small class="text-muted ml-2">
                            <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                        </small>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

app/templates/users/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <div class="form-group">
                            {{ form.email.label(class="form-control-label") }}
                            {% if form.email.errors %}
                                {{ form.email(class="form-control form-control-sm is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.email(class="form-control form-control-sm") }}
                            {% endif %}
                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info") }}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

app/templates/users/user.html
{% extends "layout.html" %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="content-section">
                <div class="form-group">
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <span class="font-weight-bold pr-3">Name: </span>{{ user.firstname }} {{ user.lastname }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <span class="font-weight-bold pr-3">Phone: </span>{{ user.phone }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <span class="font-weight-bold pr-3">Fax: </span>{{ user.fax }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <span class="font-weight-bold pr-3">Email: </span>{{ user.email }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <span class="font-weight-bold pr-3">Job Type: </span>{{ user.job_type }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <span class="font-weight-bold pr-3">Role: </span>{{ user.role }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <span class="font-weight-bold pr-3">Assigned source: </span>{{ user.source_user.name }}
                        </div>
                    </div>
                </div>
                <div class="form-row d-flex justify-content-between">
                    <div class="form-group d-flex justify-content-start">
                        <button type="button" class="btn btn-outline-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                    </div>
                    <div class="form-group d-flex justify-content-end">
                        <a class="btn btn-outline-secondary btn-sm m-1" href="{{ url_for('users.crud_user',user_id=user.id) }}">Update</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="container">
        <div class="modal fade row" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header d-flex align-items-center text-white bg-dark rounded shadow-sm">
                        <div class="lh-100">
                            <h5 class="lh-100">
                                Delete User?
                            </h5>
                        </div>
                    </div>
                    <div class="modal-footer form-row d-flex justify-content-between">
                        <div class="form-group d-flex justify-content-start">
                            <form action="{{ url_for('users.delete_user',user_id=user.id) }}" method="POST">
                                <input type="submit" class="btn btn-outline-danger" value="Delete"></button>
                            </form>
                        </div>
                        <div class="form-group d-flex justify-content-end">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

app/templates/users/users_list.html
{% extends "layout.html" %}
{% block content %}
    <div class="p-3 bg-white rounded shadow-sm content-section">
        <div class="card-body table-responsive-md" >
            <div class="form-group">
                <input type="text" id="usr_input" onkeyup="sou_search()" class="form-control input-lg" autocomplete="off" name="input" placeholder="Search"  autofocus>
            </div>
            <table Class="table table-striped table-sm">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Phone</th>
                        <th scope="col">Fax</th>
                        <th scope="col">Role</th>
                        <th scope="col">source</th>
                    </tr>
                </thead>
                <tbody id="usr_list_table">
                    {% for user in users %}
                        <tr>
                            <td><a href="{{ url_for('users.user', user_id=user.id)}}">{{ user.firstname }} {{ user.lastname }}</a></th>
                            <td>{{ user.email}}</td>
                            <td>{{ user.phone }}</td>
                            <td>{{ user.fax }}</td>
                            <td>{{ user.role }}</td>
                            <td><a href="{{ url_for('sources.source', source_id=user.source_id)}}">{{ user.source_user.name }}</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}