app/sources/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, SubmitField
from wtforms.validators import DataRequired, Length


state_list = [('AL','Alabama'),('AK','Alaska'),('AZ','Arizona'),('AR','Arkansas'),('CA','California'),('CO','Colorado'),('CT','Connecticut'),('DE','Delaware'),('DC','District Of Columbia'),('FL','Florida'),('GA','Georgia'),('HI','Hawaii'),('ID','Idaho'),('IL','Illinois'),('IN','Indiana'),('IA','Iowa'),('KS','Kansas'),('KY','Kentucky'),('LA','Louisiana'),('ME','Maine'),('MD','Maryland'),('MA','Massachusetts'),('MI','Michigan'),('MN','Minnesota'),('MS','Mississippi'),('MO','Missouri'),('MT','Montana'),('NE','Nebraska'),('NV','Nevada'),('NH','New Hampshire'),('NJ','New Jersey'),('NM','New Mexico'),('NY','New York'),('NC','North Carolina'),('ND','North Dakota'),('OH','Ohio'),('OK','Oklahoma'),('OR','Oregon'),('PA','Pennsylvania'),('RI','Rhode Island'),('SC','South Carolina'),('SD','South Dakota'),('TN','Tennessee'),('TX','Texas'),('UT','Utah'),('VT','Vermont'),('VA','Virginia'),('WA','Washington'),('WV','West Virginia'),('WI','Wisconsin'),('WY','Wyoming')]
source_list = [('alf','ALF'),('hospital','Hospital'),('pcp','PCP'),('snf','SNF'),('specialist','Specialist'),('sacrehab','Sac Rehab')]

class SourceForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(min=2, max=50)])
    address1 = StringField('Address 1', validators=[Length(min=2, max=20)])
    address2 = StringField('Address 2')
    city = StringField('City')
    state = SelectField('State',choices=state_list)
    zip_code = StringField('Zip Code')
    source= SelectField('Source',choices=source_list)
    submit = SubmitField('Save')

app/sources/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, fresh_login_required
from app import db
from app.models import Source, User, Referral
from app.sources.forms import SourceForm


sources = Blueprint('sources', __name__)


@sources.route("/sources/list")
@fresh_login_required
def list_source():
    user = User.query.get(current_user.id)
    if user.role == 'admin':
        sources = Source.query.all()
        return render_template('sources/source_list.html', title="Source", sources=sources)
    else:
        abort(403)


@sources.route("/sources/new", methods=['GET', 'POST'])
@fresh_login_required
def new_source():
    form = SourceForm()
    if form.validate_on_submit():
        source = Source(name=form.name.data,address1=form.address1.data, address2=form.address2.data, city=form.city.data, state=form.state.data, zip_code=form.zip_code.data, source=form.source.data)
        db.session.add(source)
        db.session.commit()
        flash('The Source was created successfully.', 'success')
        return redirect(url_for('main.home'))
    return render_template('sources/crud_source.html', title='Create Source', form=form)


@sources.route("/sources/<int:source_id>")
@fresh_login_required
def source(source_id):
    source = Source.query.get_or_404(source_id)
    return render_template('sources/source.html', title=f"{source.name}", source=source)


@sources.route("/sources/<int:source_id>/update", methods=['GET', 'POST'])
@fresh_login_required
def update_source(source_id):
    source = Source.query.get_or_404(source_id)
    if current_user.role != 'admin':
         abort(403)
    form = SourceForm()
    if form.validate_on_submit():
        source.name=form.name.data
        source.address1=form.address1.data
        source.address2=form.address2.data
        source.city=form.city.data
        source.state=form.state.data
        source.zip_code=form.zip_code.data
        source.source=form.source.data
        db.session.commit()
        flash('The Source was updated successfully.', 'success')
        return redirect(url_for('sources.source',source_id=source_id))
    elif request.method == 'GET':
        form.name.data=source.name
        form.address1.data=source.address1
        form.address2.data=source.address2
        form.city.data=source.city
        form.state.data=source.state
        form.zip_code.data=source.zip_code
        form.source.data=source.source
    return render_template('sources/crud_source.html', title='Update Source', form=form)

@sources.route("/sources/<int:source_id>/delete", methods=['POST'])
@fresh_login_required
def delete_source(source_id):
    source = Source.query.get_or_404(source_id)
    if current_user.role != 'admin':
        abort(403)
    db.session.delete(source)
    db.session.commit()
    flash('The Source was deleted successfully.', 'success')
    return redirect(url_for('sources.list_source'))

app/templates/sources/crud_source.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="content-section">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <div class="form-row">
                    <div class="form-group col-md-12">
                        {{ form.name.label(class="form-control-label") }}
                        {% if form.name.errors %}
                            {{ form.name(class="form-control form-control-sm is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.name.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.name(class="form-control form-control-sm") }}
                        {% endif %}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-12">
                        {{ form.address1.label(class="form-control-label") }}
                        {% if form.address1.errors %}
                            {{ form.address1(class="form-control form-control-sm is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.address1.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.address1(class="form-control form-control-sm") }}
                        {% endif %}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-12">
                        {{ form.address2.label(class="form-control-label") }}
                        {% if form.address2.errors %}
                            {{ form.address2(class="form-control form-control-sm is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.address2.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.address2(class="form-control form-control-sm") }}
                        {% endif %}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-4">
                        {{ form.city.label(class="form-control-label") }}
                        {% if form.city.errors %}
                            {{ form.city(class="form-control form-control-sm is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.city.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.city(class="form-control form-control-sm") }}
                        {% endif %}
                    </div>
                    <div class="form-group col-md-4">
                        {{ form.state.label(class="form-control-label") }}
                        {% if form.state.errors %}
                            {{ form.state(class="form-control form-control-sm is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.state.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.state(class="form-control form-control-sm") }}
                        {% endif %}
                    </div>
                    <div class="form-group col-md-4">
                        {{ form.zip_code.label(class="form-control-label") }}
                        {% if form.zip_code.errors %}
                            {{ form.zip_code(class="form-control form-control-sm is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.zip_code.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.zip_code(class="form-control form-control-sm") }}
                        {% endif %}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-3">
                        {{ form.source.label(class="form-control-label") }}
                        {% if form.source.errors %}
                            {{ form.source(class="form-control form-control-sm is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.source.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.source(class="form-control form-control-sm") }}
                        {% endif %}
                    </div>
                </div>
                <div class="form-row d-flex justify-content-end">
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info") }}
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

app/templates/sources/source.html
{% extends "layout.html" %}
{% block content %}
    <div class="row my-3 p-3 bg-white rounded shadow-sm">
        <div class="col-md-12">
            <div class="content-section">
                <div class="form-group">
                    <div class="form-row">
                        <legend class="col-form-label col-md-12 p-1 my-1 text-white bg-secondary rounded shadow-sm">Source Info</legend>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <span class="font-weight-bold pr-3">Name: </span>{{ source.name }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <span class="font-weight-bold pr-3">Address: </span>{{ source.address1 }} {{ source.address2 }}, {{ source.city }}, {{ source.state }} {{ source.zip_code }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <span class="font-weight-bold pr-3">Source: </span>{{ source.source.upper() }}
                        </div>
                    </div>
                </div>
                <div class="form-row d-flex justify-content-between">
                    <div class="form-group d-flex justify-content-start">
                        <button type="button" class="btn btn-outline-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                    </div>
                    <div class="form-group d-flex justify-content-end">
                        <a class="btn btn-outline-secondary btn-sm m-1" href="{{ url_for('sources.update_source',source_id=source.id) }}">Update</a>
                    </div>
                </div>
                <div class="form-row">
                    <legend class="col-form-label col-md-12 p-1 my-1 text-white bg-secondary rounded shadow-sm">Users</legend>
                </div>
                <table Class="table table-striped table-sm">
                    <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Email</th>
                            <th scope="col">Phone</th>
                            <th scope="col">Fax</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in source.users %}
                        <tr>
                            <th scope="col"><a href="{{ url_for('users.user', user_id=user.id)}}">{{ user.firstname }} {{ user.lastname }}</a></th>
                            <td>{{ user.email}}</td>
                            <td>{{ user.phone }}</td>
                            <td>{{ user.fax }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="container">
        <div class="modal fade row" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header d-flex align-items-center text-white bg-dark rounded shadow-sm">
                        <div class="lh-100">
                            <h5 class="lh-100">
                                Delete Source?
                            </h5>
                        </div>
                    </div>
                    <div class="modal-body d-flex align-items-center">
                        <div class="lh-100">
                            <small class="lh-100">
                                <p>This will delete all <strong>USERS</strong> assigned to this Source.</p>
                            </small>
                        </div>
                    </div>
                    <div class="modal-footer form-row d-flex justify-content-between">
                        <div class="form-group d-flex justify-content-start">
                            <form action="{{ url_for('sources.delete_source',source_id=source.id) }}" method="POST">
                                <input type="submit" class="btn btn-outline-danger" value="Delete"></button>
                            </form>
                        </div>
                        <div class="form-group d-flex justify-content-end">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

app/templates/sources/source_list.html
{% extends "layout.html" %}
{% block content %}
    <div class="my-3 p-3 bg-white rounded shadow-sm content-section">
        <div class="card-body table-responsive-md" >
            <div class="form-group">
                <input type="text" id="sou_input" onkeyup="sou_search()" class="form-control input-lg" autocomplete="off" name="input" placeholder="Search"  autofocus>
            </div>
            <table Class="table table-striped table-sm">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Address</th>
                        <th scope="col">City</th>
                        <th scope="col">State</th>
                        <th scope="col">Zip Code</th>
                        <th scope="col">Source</th>
                    </tr>
                </thead>
                <tbody id="sou_list_table">
                    {% for source in sources %}
                        <tr>
                            <td><a href="{{ url_for('sources.source', source_id=source.id)}}">{{ source.name }}</a></th>
                            <td>{{ source.address1}} {{ source.address2}}</td>
                            <td>{{ source.city }}</td>
                            <td>{{ source.state }}</td>
                            <td>{{ source.zip_code }}</td>
                            <td>{{ source.source }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}