app/main/routes.py
from flask import render_template, url_for, flash, redirect, Blueprint
from flask_login import current_user
from app import db
from app.models import User, Referral, Source

main = Blueprint('main', __name__)



@main.route("/")
@main.route("/home")
def home():
    if current_user.is_authenticated:
        return redirect(url_for('referrals.list_referrals'))
    return redirect(url_for('users.login'))

app/sources/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, fresh_login_required
from app import db
from app.models import Source, User, Referral
from app.sources.forms import SourceForm


sources = Blueprint('sources', __name__)


@sources.route("/sources/list")
@fresh_login_required
def list_source():
    user = User.query.get(current_user.id)
    if user.role == 'admin':
        sources = Source.query.all()
        return render_template('sources/source_list.html', title="Source", sources=sources)
    else:
        abort(403)


@sources.route("/sources/new", methods=['GET', 'POST'])
@fresh_login_required
def new_source():
    form = SourceForm()
    if form.validate_on_submit():
        source = Source(name=form.name.data,address1=form.address1.data, address2=form.address2.data, city=form.city.data, state=form.state.data, zip_code=form.zip_code.data, source=form.source.data)
        db.session.add(source)
        db.session.commit()
        flash('The Source was created successfully.', 'success')
        return redirect(url_for('main.home'))
    return render_template('sources/crud_source.html', title='Create Source', form=form)


@sources.route("/sources/<int:source_id>")
@fresh_login_required
def source(source_id):
    source = Source.query.get_or_404(source_id)
    return render_template('sources/source.html', title=f"{source.name}", source=source)


@sources.route("/sources/<int:source_id>/update", methods=['GET', 'POST'])
@fresh_login_required
def update_source(source_id):
    source = Source.query.get_or_404(source_id)
    if current_user.role != 'admin':
         abort(403)
    form = SourceForm()
    if form.validate_on_submit():
        source.name=form.name.data
        source.address1=form.address1.data
        source.address2=form.address2.data
        source.city=form.city.data
        source.state=form.state.data
        source.zip_code=form.zip_code.data
        source.source=form.source.data
        db.session.commit()
        flash('The Source was updated successfully.', 'success')
        return redirect(url_for('sources.source',source_id=source_id))
    elif request.method == 'GET':
        form.name.data=source.name
        form.address1.data=source.address1
        form.address2.data=source.address2
        form.city.data=source.city
        form.state.data=source.state
        form.zip_code.data=source.zip_code
        form.source.data=source.source
    return render_template('sources/crud_source.html', title='Update Source', form=form)

@sources.route("/sources/<int:source_id>/delete", methods=['POST'])
@fresh_login_required
def delete_source(source_id):
    source = Source.query.get_or_404(source_id)
    if current_user.role != 'admin':
        abort(403)
    db.session.delete(source)
    db.session.commit()
    flash('The Source was deleted successfully.', 'success')
    return redirect(url_for('sources.list_source'))

app/users/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, session, Blueprint
from flask_login import login_user, current_user, logout_user, fresh_login_required
from app import app, db, bcrypt
from app.models import User, Referral, Source
from app.users.forms import LoginForm, UserForm, RequestResetForm, ResetPasswordForm
from app.utils import send_reset_email, send_new_account_email

users = Blueprint('users', __name__)


@users.route("/user/list")
@fresh_login_required
def list_users():
    user = User.query.get(current_user.id)
    if user.role == 'admin':      
        users = User.query.all()
        return render_template('users/users_list.html', title="Users", users=users)
    else:
        abort(403)


@users.route("/user/new", methods=['GET', 'POST'])
@fresh_login_required
def new_user():
    sources = Source.query.all()
    form = UserForm()
    if form.validate_on_submit():
        user = User(firstname=form.firstname.data,lastname=form.lastname.data, email=form.email.data.lower(), phone=form.phone.data, fax=form.fax.data, role=form.role.data, source_id=form.source_id.data)
        db.session.add(user)
        db.session.commit()
        send_new_account_email(user)
        flash('The User was created successfully.', 'success')
        return redirect(url_for('users.login'))
    return render_template('users/crud_user.html', title='Create User', form=form, sources=sources)


@users.route("/user/<int:user_id>")
@fresh_login_required
def user(user_id):
    user = User.query.get_or_404(user_id)
    return render_template('users/user.html', title="User Info", user=user)


@users.route("/user/<int:user_id>/update", methods=['GET', 'POST'])
@fresh_login_required
def crud_user(user_id):
    user = User.query.get_or_404(user_id)
    if current_user.role != 'admin':
         abort(403)
    form = UserForm()
    if form.validate_on_submit():
        user.firstname=form.firstname.data
        user.lastname=form.lastname.data
        user.email=form.email.data.lower()
        user.phone=form.phone.data
        user.fax=form.fax.data
        user.job_type=form.job_type.data
        user.role=form.role.data
        user.source_id=form.source_id.data
        db.session.commit()
        flash('The User was updated successfully.', 'success')
        return redirect(url_for('users.user',user_id=user.id))
    elif request.method == 'GET':
        sources = Source.query.all()
        form.firstname.data=user.firstname
        form.lastname.data=user.lastname
        form.email.data=user.email
        form.phone.data=user.phone
        form.fax.data=user.fax
        form.job_type.data=user.job_type
        form.role.data=user.role
        form.source_id.data=user.source_id
    return render_template('users/crud_user.html', title='Update User', form=form)


@users.route("/user/<int:user_id>/delete", methods=['POST'])
@fresh_login_required
def delete_user(user_id):
    user = User.query.get_or_404(user_id)
    if current_user.role != 'admin':
        abort(403)
    db.session.delete(user)
    db.session.commit()
    flash('The User was deleted successfully.', 'success')
    return redirect(url_for('users.list_users'))


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password.', 'danger')
    return render_template('users/login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

                
@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():    
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('users/reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('users/reset_token.html', title='Reset Password', form=form) 

app/templates/layout.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
	<meta name="description" content="Patient Intake Tool" />
	<meta name="keywords" content="HTML,CSS,Python,JavaScript,jQuery,MySQL" />
	<meta name="author" content="Ryan Hafen" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="theme-color" content="#ffffff" />

    <!-- Icon Image -->
    <link rel="icon" href="{{ url_for('static', filename='img/logo.png') }}"  type="image/png" sizes="16x16" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" />
    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">

    <!-- Title -->
    {% if title %}
        <title>Patient Intake Tool - {{ title }}</title>
    {% else %}
        <title>Patient Intake Tool</title>
    {% endif %}
</head>
<body>
    <header class="site-header border-bottom">
        <nav class="navbar navbar-expand-lg navbar-light bg-darkgray align-items-end">
            <a class="navbar-brand" href="{{ url_for('main.home') }}"><img src="{{ url_for('static', filename='img/logo.png') }}" width="180" height="120" alt=""></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
                    </li>
                    {% if current_user.is_authenticated and current_user.role == 'admin' %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Referrals</a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="{{ url_for('referrals.list_referrals') }}">Referrals</a>
                                <a class="dropdown-item" href="{{ url_for('referrals.new_referral') }}">New Referral</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Users</a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="{{ url_for('users.list_users') }}">Users</a>
                                <a class="dropdown-item" href="{{ url_for('users.new_user') }}">New User</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Source</a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="{{ url_for('sources.list_source') }}">Source</a>
                                <a class="dropdown-item" href="{{ url_for('sources.new_source') }}">New Source</a>
                            </div>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a></li>
                    {% elif current_user.is_authenticated and current_user.role == 'source' %}
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('referrals.new_referral') }}">New Referral</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('referrals.list_referrals') }}">My Referrals</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a></li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
                        </li>
                    {% endif %}
                </ul >
            </div>
        </nav>
        {% with messages =  get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                        <div class="alert alert-{{ category }} alert-dismissible flash_message">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                                {{message}}
                            </div>
                        </div>
                {% endfor %}
            {% endif%}
        {% endwith %}
    </header>
    <main class="container mb-5 min-height-600">
        <div class="d-flex align-items-center p-3 my-3 text-white bg-darkslategray rounded shadow-sm">
            <div class="lh-100">
                <h5 class="lh-100">
                    {{ title }}
                </h5>
            </div>
        </div>
        {% block content %}
        {% endblock %}
    </main>
    <footer class="footer opacity-50">
        <div class="container text-center">
            <a href="#"><img src="{{ url_for('static', filename='img/hsl-logo-tran-min.png') }}" width="96" height="28.5" alt=""></a>
        </div>
    </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/helpers.js') }}"></script>
</body>
</html>